# Generated by Django 2.2.5 on 2019-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lotto_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=0)),
                ('prize1', models.IntegerField(default=0)),
                ('prize2', models.IntegerField(default=0)),
                ('prize3', models.IntegerField(default=0)),
                ('prize4', models.IntegerField(default=0)),
                ('prize5', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('drawing_day', models.DateTimeField()),
            ],
        ),
    ]
