# Generated by Django 2.2.5 on 2019-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getCron', '0002_lotto_data_prize6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotto_data',
            name='drawing_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
